default:
  suites:
    default:
      paths:
        features: '%paths.base%/../tests/Behat/Features'
      contexts:
        - Mollie\Shopware\Behat\BootstrapContext
        - Mollie\Shopware\Behat\PaymentContext
        - Mollie\Shopware\Behat\CustomerContext
        - Mollie\Shopware\Behat\CheckoutContext